# Generated by Django 6.0.1 on 2026-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('images', models.JSONField(default=list)),
                ('sku', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('revs_count', models.IntegerField(blank=True, null=True)),
                ('diagonal', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('specifications', models.JSONField(default=dict)),
            ],
        ),
    ]
